---
title: "rsaga terrain basic"
output: html_document
date: "2023-02-24"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls()) ### (you may not want this line) clear workspace   CAUTION!!!
```
# Overview


# Packages
```{r}
library(RSAGA)
library(gdalUtilities)
library(terra)
library(sf)
```


# Rsaga 
This RSAGA version has been tested with SAGA GIS versions between 2.3.1 and 8.4.1.
```{r}
rsaga.path <- "C:/Program Files/SAGA"
```

```{r}
env <- rsaga.env(path=rsaga.path) 
```

```{r}
rsaga.get.modules("ta_mo")
```

```{r}
get
```



# Aspect Slope Curvature
Simple
```{r}
rsaga.slope.asp.curv(in.dem="../data/dems/DEMClippedEA_NWT2014.asc", 
                     out.aspect = "../outputs/EqualArea/basic/aspect",
                     out.slope = "../outputs/EqualArea/basic/slope",
                     out.cprof = "../outputs/EqualArea/basic/cprof",
                     out.cplan = "../outputs/EqualArea/basic/cplan",
                     method = "poly2zevenbergen",
                     unit.slope = "radians",
                     unit.aspect = "radians",
                     env = env)
```

Too large for current disk space
```{r eval=FALSE, include=FALSE}
rsaga.slope.asp.curv(in.dem="../data/dems/DEMClippedEA_NWT2014.asc", 
                     out.aspect = "../outputs/EqualArea/basic/aspect",
                     out.slope = "../outputs/EqualArea/basic/slope",
                     out.cgene = "../outputs/EqualArea/basic/cgene",
                     out.cprof = "../outputs/EqualArea/basic/cprof",
                     out.cplan = "../outputs/EqualArea/basic/cplan",
                     out.ctang = "../outputs/EqualArea/basic/ctang",
                     out.clong = "../outputs/EqualArea/basic/clong",
                     out.ccros = "../outputs/EqualArea/basic/ccros",
                     out.cmini = "../outputs/EqualArea/basic/cmini",
                     out.cmaxi = "../outputs/EqualArea/basic/cmaxi",
                     out.ctota = "../outputs/EqualArea/basic/ctota",
                     out.croto = "../outputs/EqualArea/basic/croto",
                     method = "poly2zevenbergen",
                     unit.slope = "radians",
                     unit.aspect = "radians",
                     env = env)
```




