---
title: "SAGA Grids to ASCii"
output: html_document
date: "2023-02-25"
---

```{r}
rm(list=ls()) ### (you may not want this line) clear workspace   CAUTION!!!
```

# Overview


# Packages
```{r}
library(RSAGA)
library(gdalUtilities)
library(terra)
library(sf)
```

```{r}
rsaga.path <- "C:/Users/atalucci/Documents/Programs/saga-8.5.1_x64"
```

```{r}
env <- rsaga.env(path=rsaga.path) 
```


# To ASCii
## Basic
```{r}
rsaga.sgrd.to.esri(in.sgrds = "../outputs/slope_EA_SK", out.grids = "../outputs/slope_EA_SK", format = "ascii", env = env)
```

```{r}
rsaga.sgrd.to.esri(in.sgrds = "../outputs/cprof_EA_SK", out.grids = "../outputs/cprof_EA_SK", format = "ascii", env = env)
```

```{r}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/cplan_EA_SK", out.grids = "../outputs/cplan_EA_SK", format = "ascii", env = env)
```

```{r}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/aspect_EA_SK", out.grids = "../outputs/aspect_EA_SK", format = "ascii", env = env)
```

# Additional Basic
```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds = "../outputs/cgene", out.grids = "../outputs/cgene", format = "ascii", env = env)
```

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds = "../outputs/ctang", out.grids = "../outputs/ctang", format = "ascii", env = env)
```

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/clong", out.grids = "../outputs/clong", format = "ascii", env = env)
```

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/ccros", out.grids = "../outputs/ccros", format = "ascii", env = env)
```


```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds = "../outputs/cmini", out.grids = "../outputs/cmini", format = "ascii", env = env)
```

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds = "../outputs/cmaxi", out.grids = "../outputs/cmaxi", format = "ascii", env = env)
```

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/ctota", out.grids = "../outputs/ctota", format = "ascii", env = env)
```

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/croto", out.grids = "../outputs/croto", format = "ascii", env = env)
```


## Hydro

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/carea", out.grids = "../outputs/carea", format = "ascii", env = env)
```


```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds = "../outputs/mean", out.grids = "../outputs/mean", format = "ascii", env = env)
```

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds = "../outputs/totmat", out.grids = "../outputs/totmat", format = "ascii", env = env)
```

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/accleft", out.grids = "../outputs/accleft", format = "ascii", env = env)
```

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/accright", out.grids = "../outputs/accright", format = "ascii", env = env)
```

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/flowpath", out.grids = "../outputs/flowpath", format = "ascii", env = env)
```

## SWI

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/SWIC", out.grids = "../outputs/SWIC1", format = "ascii", env = env)
```


```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/SWIL_EA_AK", out.grids = "../outputs/SWIL_EA_AK", format = "ascii", env = env)
```

## Pisr

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/PisrDiffuse", out.grids = "../outputs/PisrDiffuse", format = "ascii", env = env)
```

```{r eval=FALSE, include=FALSE}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/PisrDirect", out.grids = "../outputs/PisrDirect", format = "ascii", env = env)
```


# SWI FOR SK Split
```{r}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/SWIL_EA_SK_bp1", out.grids = "../outputs//SWIL_EA_SK_bp1", format = "ascii", env = env)
```

```{r}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/SWIL_EA_SK_ss1", out.grids = "../outputs//SWIL_EA_SK_ss1", format = "ascii", env = env)
```

```{r}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/SWIL_EA_SK_ss2", out.grids = "../outputs//SWIL_EA_SK_ss2", format = "ascii", env = env)
```

```{r}
rsaga.sgrd.to.esri(in.sgrds =  "../outputs/SWIL_EA_SK_ssbp1", out.grids = "../outputs//SWIL_EA_SK_ssbp1", format = "ascii", env = env)
```

