---
title: "Wetness Index"
output: html_document
date: "2023-02-27"
---



```{r}
rm(list=ls()) ### (you may not want this line) clear workspace   CAUTION!!!
```

# Overview


# Packages
```{r}
library(RSAGA)
library(gdalUtilities)
library(terra)
library(sf)
```


# Rsaga 
This RSAGA version has been tested with SAGA GIS versions between 2.3.1 and 8.4.1.
```{r}
rsaga.path <- "C:/Users/atalucci/Documents/Programs/saga-8.5.1_x64"
```

```{r}
env <- rsaga.env(path=rsaga.path) 
```

# Wetness index
Can change slope.type to = "catchment"
```{r}
rsaga.wetness.index(in.dem="../data/dems/FABDEM_EA_AK.asc", 
                    out.wetness.index = "../outputs/SWIL_EA_AK",  
                    slope.type="local", 
                    env = env)
```

# 2. Saga Grid to ASCII
```{r}
rm(list=ls()) ### (you may not want this line) clear workspace   CAUTION!!!
```

## Packages
```{r}
library(RSAGA)
library(gdalUtilities)
library(terra)
library(sf)
```

```{r}
rsaga.path <- "C:/Users/atalucci/Documents/Programs/saga-8.5.1_x64"
```

```{r}
env <- rsaga.env(path=rsaga.path) 
```



## Slope
```{r}
rsaga.sgrd.to.esri(in.sgrds = "../outputs/SWIL_EA_AK", out.grids = "../outputs/SWIL_EA_AK", format = "ascii", env = env)
```



### Aspect
```{r}
swil<-rast("../outputs/SWIL_EA_AK.asc")
```


```{r}
writeRaster(swil, filename="../outputs/SWIL_EA_AK.tif", filetype = "GTiff", overwrite=TRUE)
```